config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :players do
    collection do
      get :search_by
    end
  end
  resources :devices do
    collection do
      get :search_by
    end
  end
  resources :offers do
    collection do
      get :payout_with_age_range
    end
  end
  resources :offer_targets
  root "players#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/device.rb
# frozen_string_literal: true

class Device < ApplicationRecord
  belongs_to :player

  OPERATING_SYSTEMS = %w[ios android].freeze

  validates :modelname, presence: true
  validates :operating_system, inclusion: { in: OPERATING_SYSTEMS }
  validates :os_version, presence: true, format: { with: /(\d+\.)(\d+\.)(\d+)/, message: 'Use the syntax: 1.0.0' }
  validates :locale, presence: true, format: { with: /[a-z]{2}_[A-Z]{2}/, message: 'Use the syntax: fr_CA' }
end

app/models/offer.rb
# frozen_string_literal: true

class Offer < ApplicationRecord
  has_many :offer_targets, dependent: :destroy

  validates :title, :header, :description, presence: true
  validates :points, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :payout, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/offer_target.rb
# frozen_string_literal: true

class OfferTarget < ApplicationRecord
  belongs_to :offer

  enum gender: { male: 0, female: 1, non_binary: 2 }

  validates :minimum_age, :maximum_age, :locale, :gender, :minimum_os_version, :operating_system, presence: true
  validates :operating_system, inclusion: { in: Device::OPERATING_SYSTEMS }

  scope :by_age_range, ->(min, max) { where('minimum_age >= ? AND maximum_age <= ?', min, max) }

  def to_s
    "#{minimum_age}-#{maximum_age}, #{gender}, #{operating_system}, #{minimum_os_version}, #{locale}"
  end

  def min_birtdate
    minimum_age.years.ago.to_date
  end

  def max_birtdate
    maximum_age.years.ago.to_date
  end
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  GENDER_OPTIONS = %w[male female non_binary].freeze

  has_one :device, dependent: :destroy

  enum gender: { male: 0, female: 1, non_binary: 2 }

  validates :first_name, :last_name, :gender, :birthdate, presence: true
  validate :validate_birthdate

  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def validate_birthdate
    return if birthdate.nil? || birthdate < 13.years.ago.to_date

    errors.add(:base, 'Player should be over 13 years.')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
# frozen_string_literal: true

class BaseController < ApplicationController
  include BaseHandler
  include ExceptionHandler

  before_action :create_resource, only: :create
  before_action :build_resource, only: :new

  protected

  def index
    resources
  end

  def new
    resource
  end

  def edit
    resource
  end

  def create
    if resource.save
      flash[:notice] = "#{humanized_model_name} is created successfully"
      redirect_to send("#{controller_name.singularize}_path", resource.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if resource.update(permitted_params)
      flash[:notice] = "#{humanized_model_name} is updated successfully"
      redirect_to send("#{controller_name.singularize}_path", resource.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if resource.destroy
      flash[:notice] = "#{humanized_model_name} is deleted successfully"
    else
      flash[:alert] = "Unable to delete #{humanized_model_name}"
    end

    redirect_to send("#{controller_name}_path")
  end

  def show
    resource
  end

  # index method
  def resources
    @resources ||= model.page(params[:page])
  end

  # show/edit method
  def resource
    @resource ||= model.find(params[:id])
  end

  # new method
  def build_resource
    @resource = model.new
  end

  # use for create method
  def create_resource
    @resource = model.new(permitted_params)
  end

  def model
    model_name.constantize
  end

  def model_name
    controller_name.camelize.singularize
  end

  def humanized_model_name
    model_name.underscore.humanize
  end
end

app/controllers/concerns/base_handler.rb
# frozen_string_literal: true

module BaseHandler
  extend ActiveSupport::Concern

  private

  class_methods do
    def actions(*actions)
      send :public, *actions
    end
  end
end

app/controllers/concerns/exception_handler.rb
# frozen_string_literal: true

module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |_e|
      render 'shared/not_found', status: :not_found
    end
  end
end

app/controllers/devices_controller.rb
# frozen_string_literal: true

class DevicesController < BaseController
  actions :index, :show, :new, :create, :edit, :update, :destroy

  def index
    @resources = Device.includes(:player).page(params[:page])
  end

  def search_by
    min, max = params.require(:os_version_range).split('-')

    devices = Device.pluck(:os_version).filter do |os|
      Gem::Version.new(os) > Gem::Version.new(min) && Gem::Version.new(os) < Gem::Version.new(max)
    end

    render json: { count: devices.length }, status: :ok
  end

  private

  def permitted_params
    params.require(:device).permit(:modelname, :operating_system, :os_version, :locale, :player_id)
  end
end

app/controllers/offer_targets_controller.rb
# frozen_string_literal: true

class OfferTargetsController < BaseController
  actions :index, :show, :new, :create, :edit, :update, :destroy

  private

  def permitted_params
    params.require(:offer_target).permit(:minimum_age, :maximum_age, :gender,
                                         :operating_system, :minimum_os_version, :locale, :offer_id)
  end
end

app/controllers/offers_controller.rb
# frozen_string_literal: true

class OffersController < BaseController
  actions :index, :show, :new, :create, :edit, :update, :destroy

  def payout_with_age_range
    min, max = params.require(:age_range).split('-').map(&:strip)
    total_payout = OfferTarget.joins(:offer).by_age_range(min, max).sum(:payout)

    render json: { total_payout: }, status: :ok
  end

  private

  def permitted_params
    params.require(:offer).permit(:title, :header, :description, :points, :payout)
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < BaseController
  actions :index, :show, :new, :create, :edit, :update, :destroy

  def search_by
    @players = PlayersFilter.new(params[:offer_target_id]).filter

    html_response = render_to_string 'players/players', layout: false, formats: :html
    render json: { html: html_response }
  end

  private

  def permitted_params
    params.require(:player).permit(:first_name, :last_name, :birthdate, :gender)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/devices_helper.rb
# frozen_string_literal: true

module DevicesHelper
  def os_options_for_select
    options_for_select(Device::OPERATING_SYSTEMS.collect { |v| [v.upcase, v] })
  end
end

app/views/devices/_device.html.erb
<tr class='align-middle'>
  <td><%= device.modelname %></td>
  <td><%= device.operating_system %></td>
  <td><%= device.os_version %></td>
  <td><%= device.locale %></td>
  <td><%= device.player.first_name %></td>
  <td><%= link_to 'Show', device, class: 'mt-2 btn btn-outline-primary' %></td>
  <td><%= link_to 'Edit', edit_device_path(device), class: 'mt-2 btn btn-outline-primary' %></td>
  <td><%= button_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' }, class: 'mt-2 btn btn-outline-danger' %></td>
</tr>

app/views/devices/_form.html.erb
<%= form_with model: device, local: true do |form| %>
  <%= render 'shared/error_messages', resource: device %>
  <%= form.text_field :modelname, placeholder: 'Model Name', class: 'mb-3 form-control', required: true %>
  <%= form.select :operating_system, Device::OPERATING_SYSTEMS, { include_blank: 'Seletc OS' }, class: 'mb-3 form-select', required: true %>
  <%= form.text_field :os_version, placeholder: 'Os Version', class: 'mb-3 form-control', required: true %>
  <%= form.text_field :locale, placeholder: 'Locale', class: 'mb-3 form-control', required: true %>
  <%= form.collection_select :player_id,  Player.all, :id, :full_name , { include_blank: 'Select player' }, { class: 'mb-3 form-select', required: true } %>
  <%= form.submit class: 'mt-2 btn btn-outline-success' %>
  <%= link_to 'Back', :back, class: 'mt-2 btn btn-outline-secondary' %>
  <%= link_to 'Go to Devices', devices_path, class: 'mt-2 btn btn-outline-secondary' %>
<% end %>

app/views/devices/edit.html.erb
<div class='mt-5 container'>
  <div class='row'>
    <div class='col-md-4 col-md-offset-6'>
      <h3>Edit a Device</h3>
      <%= render 'form', device: @resource %>
    </div>
  </div>
</div>

app/views/devices/index.html.erb
<div class='my-5 container' data-controller='devices'>
  <h1>Devices</h1>

  <div class='row mb-3'>
    <div class='col-sm-3'>
      <h5>Filter by OS Version</h5>
    </div>
    <div class='col-sm-6'>
      <input
        type='text'
        id='os_version_range'
        placeholder='Enter version range e.g. (5.4.0 - 10.0.1)'
        data-target='devices.content'
        class='mb-3 form-control'
      />
    </div>
    <div class='col-sm-3'>
      <button class='btn btn-outline-secondary find_matching_devices' data-action='click->devices#find_devices_count'>
        Find Devices Count
      </button>
    </div>
  </div>

  <table class='table table-striped'>
    <thead class='table-dark'>
      <tr>
        <th>Model Name</th>
        <th>Operating System</th>
        <th>OS Version</th>
        <th>Locale</th>
        <th>Player First Name</th>
        <th colspan='3'></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'device', collection: @resources, as: :device %>
    </tbody>
  </table>

  <%= paginate @resources %>

  <%= link_to 'Add New Device', new_device_path, class: 'mt-2 btn btn-outline-secondary' %>
  <%= link_to 'Back', :back, class: 'mt-2 btn btn-outline-secondary' %>
</div>

<%= render 'shared/modal'%>

app/views/devices/new.html.erb
<div class='mt-5 container'>
  <div class='row'>
    <div class='col-md-4 col-md-offset-6'>
    <h3>Create a Device</h3>
    <%= render 'form', device: @new_resource %>
    </div>
  </div>
</div>

app/views/devices/show.html.erb
<div class='mt-5 container'>
  <div class='row'>
    <div class='col-md-4 col-md-offset-6'>
      <h3>Device</h3>
      <div class='mb-3'>
        <span class='font-weight-bold'>Model Name: </span>
        <%= @resource.modelname %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Operating System: </span>
        <%= @resource.operating_system %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>OS Version: </span>
        <%= @resource.os_version %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Locale: </span>
        <%= @resource.locale %>
      </div>

      <%= link_to 'Edit', edit_device_path(@resource), class:'mt-2 btn btn-outline-secondary' %>
      <%= link_to 'Back', :back, class: 'mt-2 btn btn-outline-secondary' %>
      <%= link_to 'Go to Devices', devices_path, class: 'mt-2 btn btn-outline-secondary' %>
    </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class='alert alert-danger d-flex alert-dismissible fade show align-items-center' role='alert'>
  <%= alert %>
  <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
</div>

app/views/layouts/_notice.html.erb
<div class='alert alert-success alert-dismissible fade show align-items-center' role='alert'>
  <%= notice %>
  <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge project</title>
    <meta name='viewport' content='width=device-width,initial-scale=1'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>

    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC' crossorigin='anonymous'>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>
    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js' integrity='sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM' crossorigin='anonymous'></script>
  </head>

  <body>
    <%= render 'shared/nav_bar' %>
    <div class='mt-5 container'>
      <% if notice %>
        <%= render 'layouts/notice' %>
      <% end %>
      <% if alert %>
        <%= render 'layouts/alerts' %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/offer_targets/_form.html.erb
<%= form_with model: offer_target, local: true do |form| %>
  <%= render 'shared/error_messages', resource: offer_target %>
  <%= form.text_field :minimum_age, placeholder: 'Minimum Age', class: 'mb-3 form-control', required: true %>
  <%= form.text_field :maximum_age, placeholder: 'Maximum Age', class: 'mb-3 form-control', required: true %>
  <%= form.select :gender, Player::GENDER_OPTIONS, { include_blank: 'Select gender' }, class: 'mb-3 form-select', required: true %>
  <%= form.select :operating_system, Device::OPERATING_SYSTEMS, { include_blank: 'Select OS' }, class: 'mb-3 form-select', required: true %>
  <%= form.text_field :minimum_os_version, placeholder: 'Minimum OS Version', class: 'mb-3 form-control', required: true %>
  <%= form.text_field :locale, placeholder: 'Locale', class: 'mb-3 form-control', required: true %>
  <%= form.collection_select :offer_id,  Offer.all, :id, :title , { include_blank: 'Select offer' }, {class: 'mb-3 form-select', required: true} %>
  <%= form.submit class: 'mt-2 btn btn-outline-success' %>
  <%= link_to 'Back', :back, class: 'mt-2 btn btn-outline-secondary' %>
  <%= link_to 'Go to Offer Targets', offer_targets_path, class: 'mt-2 btn btn-outline-secondary' %>
<% end %>

app/views/offer_targets/_offer_target.html.erb
<tr class='align-middle'>
  <td><%= offer_target.minimum_age %></td>
  <td><%= offer_target.maximum_age %></td>
  <td><%= offer_target.gender %></td>
  <td><%= offer_target.operating_system %></td>
  <td><%= offer_target.minimum_os_version %></td>
  <td><%= offer_target.locale %></td>
  <td><%= link_to 'Show', offer_target, class: 'mt-2 btn btn-outline-primary' %></td>
  <td><%= link_to 'Edit', edit_offer_target_path(offer_target), class: 'mt-2 btn btn-outline-primary' %></td>
  <td><%= button_to 'Destroy', offer_target, method: :delete, data: { confirm: 'Are you sure?' }, class: 'mt-2 btn btn-outline-danger' %></td>
</tr>

app/views/offer_targets/edit.html.erb
<div class='mt-5 container'>
  <div class='row'>
    <div class='col-md-4 col-md-offset-6'>
      <h3>Edit an Offer Target</h3>
      <%= render 'form', offer_target: @resource %>
    </div>
  </div>
</div>

app/views/offer_targets/index.html.erb
<div class='my-5 container'>
  <h1>Offer Targets</h1>
  <table class='table table-striped'>
    <thead class='table-dark'>
      <tr>
        <th>Minimum Age</th>
        <th>Maximum Age</th>
        <th>Gender</th>
        <th>Operating System</th>
        <th>Minimum OS Version</th>
        <th>Locale</th>
        <th colspan='3'></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'offer_target', collection: @resources, as: :offer_target %>
    </tbody>
  </table>

  <%= paginate @resources %>

  <%= link_to 'Add New offer_target', new_offer_target_path, class: 'mt-2 btn btn-outline-secondary' %>
  <%= link_to 'Back', :back, class: 'mt-2 btn btn-outline-secondary' %>
</div>

app/views/offer_targets/new.html.erb
<div class='mt-5 container'>
  <div class='row'>
    <div class='col-md-4 col-md-offset-6'>
    <h3>Create an Offer Target</h3>
    <%= render 'form', offer_target: @new_resource %>
    </div>
  </div>
</div>

app/views/offer_targets/show.html.erb
<div class='mt-5 container'>
  <div class='row'>
    <div class='col-md-4 col-md-offset-6'>
      <h3>Offer Target</h3>
      <div class='mb-3'>
        <span class='font-weight-bold'>Minimum Age: </span>
        <%= @resource.minimum_age %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Maximum Age: </span>
        <%= @resource.maximum_age %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>gender: </span>
        <%= @resource.gender %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Operating System: </span>
        <%= @resource.operating_system %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Minimum OS Version: </span>
        <%= @resource.minimum_os_version %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Locale: </span>
        <%= @resource.locale %>
      </div>

      <%= link_to 'Edit', edit_offer_target_path(@resource), class:'mt-2 btn btn-outline-secondary' %>
      <%= link_to 'Back', :back, class: 'mt-2 btn btn-outline-secondary' %>
      <%= link_to 'Go to Offer Targets', offer_targets_path, class: 'mt-2 btn btn-outline-secondary' %>
    </div>
  </div>
</div>

app/views/offers/_form.html.erb
<%= form_with model: offer, local: true do |form| %>
  <%= render 'shared/error_messages', resource: offer %>
  <%= form.text_field :title, placeholder: 'Title', class: 'mb-3 form-control', required: true %>
  <%= form.text_field :header, placeholder: 'Header', class: 'mb-3 form-control', required: true %>
  <%= form.text_area :description, size: '50x3', placeholder: 'Description', class: 'mb-3 form-control' %>
  <%= form.text_field :points, placeholder: 'Points', class: 'mb-3 form-control', required: true %>
  <%= form.text_field :payout, placeholder: 'Payout', class: 'mb-3 form-control', required: true %>
  <%= form.submit class: 'mt-2 btn btn-outline-success' %>
  <%= link_to 'Back', :back, class: 'mt-2 btn btn-outline-secondary' %>
  <%= link_to 'Go to Offers', offers_path, class: 'mt-2 btn btn-outline-secondary' %>
<% end %>

app/views/offers/_offer.html.erb
<tr class='align-middle'>
  <td><%= offer.title %></td>
  <td><%= offer.header %></td>
  <td><%= offer.description %></td>
  <td><%= offer.points %></td>
  <td><%= offer.payout %></td>
  <td><%= link_to 'Show', offer, class: 'mt-2 btn btn-outline-primary' %></td>
  <td><%= link_to 'Edit', edit_offer_path(offer), class: 'mt-2 btn btn-outline-primary' %></td>
  <td><%= button_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'mt-2 btn btn-outline-danger' %></td>
</tr>

app/views/offers/edit.html.erb
<div class='mt-5 container'>
  <div class='row'>
    <div class='col-md-4 col-md-offset-6'>
      <h3>Edit an Offer</h3>
      <%= render 'form', offer: @resource %>
    </div>
  </div>
</div>

app/views/offers/index.html.erb
<div class='my-5 container' data-controller='offers'>
  <h1>Offers</h1>
  <div class='row mb-3'>
    <div class='col-sm-3'>
      <h5>Check payout by age range:</h5>
    </div>
    <div class='col-sm-6'>
      <input type='text' id='age-range-input' placeholder='Enter age range e.g. (13-35)' class='mb-3 form-control' />
    </div>
    <div class='col-sm-3'>
      <button class='btn btn-outline-secondary total-payout-btn' data-action='click->offers#total_payout_by_age_range'>
        Total payout
      </button>
    </div>
  </div>

  <table class='table table-striped'>
    <thead class='table-dark'>
      <tr>
        <th>Title</th>
        <th>Header</th>
        <th>Description</th>
        <th>Points</th>
        <th>Payout</th>
        <th colspan='3'></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'offer', collection: @resources, as: :offer %>
    </tbody>
  </table>

  <%= paginate @resources %>

  <%= link_to 'Add New Offer', new_offer_path, class: 'mt-2 btn btn-outline-secondary' %>
  <%= link_to 'Back', :back, class: 'mt-2 btn btn-outline-secondary' %>
</div>

<%= render 'shared/modal' %>

app/views/offers/show.html.erb
<div class='mt-5 container'>
  <div class='row'>
    <div class='col-md-4 col-md-offset-6'>
      <h3>Offer</h3>
      <div class='mb-3'>
        <span class='font-weight-bold'>Title: </span>
        <%= @resource.title %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Header: </span>
        <%= @resource.header %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Description: </span>
        <%= @resource.description %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Points: </span>
        <%= @resource.points %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Payout: </span>
        <%= @resource.payout %>
      </div>

      <%= link_to 'Edit', edit_offer_path(@resource), class:'mt-2 btn btn-outline-secondary' %>
      <%= link_to 'Back', :back, class: 'mt-2 btn btn-outline-secondary' %>
      <%= link_to 'Go to Offers', offers_path, class: 'mt-2 btn btn-outline-secondary' %>
    </div>
  </div>
</div>

app/views/players/_form.html.erb
<%= form_with model: player, local: true do |form| %>
  <%= render 'shared/error_messages', resource: player %>
  <%= form.text_field :first_name, placeholder: 'First Name', class: 'mb-3 form-control', required: true %>
  <%= form.text_field :last_name, placeholder: 'Last Name', class: 'mb-3 form-control', required: true %>
  <%= form.date_field :birthdate, placeholder: 'Date of Birth', class: 'mb-3 form-control', required: true %>
  <%= form.select :gender, Player::GENDER_OPTIONS, { include_blank: 'Select gender' }, class: 'mb-3 form-select', required: true %>
  <%= form.submit class: 'mt-2 btn btn-outline-success' %>
  <%= link_to 'Back', :back, class: 'mt-2 btn btn-outline-secondary' %>
  <%= link_to 'Go to Players', players_path, class: 'mt-2 btn btn-outline-secondary' %>
<% end %>

app/views/players/_player.html.erb
<tr class='align-middle'>
  <td><%= player.first_name %></td>
  <td><%= player.last_name %></td>
  <td><%= player.birthdate %></td>
  <td><%= player.gender %></td>
  <td><%= link_to 'Show', player, class: 'mt-2 btn btn-outline-primary' %></td>
  <td><%= link_to 'Edit', edit_player_path(player), class: 'mt-2 btn btn-outline-primary' %></td>
  <td><%= button_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' }, class: 'mt-2 btn btn-outline-danger' %></td>
</tr>

app/views/players/index.html.erb
<div class='my-5 container' data-controller='players'>
  <h1>Players</h1>

  <div class='row mb-3'>
    <div class='col-sm-3'>
      <h5>Filter by offer target</h5>
    </div>
    <div class='col-sm-6'>
      <%= collection_select(:offer_target, :id, OfferTarget.all, :id, :to_s,
                            { include_blank: 'Select' },
                            { class: 'form-select search-by-offer-target',
                              data: { action: 'change->players#filter_by_offer_target' } }) %>
    </div>
  </div>

  <table class='table table-striped players'>
    <thead class='table-dark'>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Date of Birth</th>
        <th>Gender</th>
        <th colspan='3'></th>
      </tr>
    </thead>
    <tbody>
      <% unless @resources.length%>
        <tr class='text-center'>
          <td colspan='7'>No player found!</td>
        </tr>
      <% end %>
      <%= render partial: 'player', collection: @resources, as: :player %>
    </tbody>
  </table>

  <%= paginate @resources %>

  <%= link_to 'Add New player', new_player_path, class: 'mt-2 btn btn-outline-secondary' %>
  <%= link_to 'Back', :back, class: 'mt-2 btn btn-outline-secondary' %>
</div>

app/views/players/show.html.erb
<div class='mt-5 container'>
  <div class='row'>
    <div class='col-md-4 col-md-offset-6'>
      <h3>Player</h3>
      <div class='mb-3'>
        <span class='font-weight-bold'>First Name: </span>
        <%= @resource.first_name %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Last Name: </span>
        <%= @resource.last_name %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Date of Birth: </span>
        <%= @resource.birthdate %>
      </div>
      <div class='mb-3'>
        <span class='font-weight-bold'>Gender: </span>
        <%= @resource.gender %>
      </div>

      <%= link_to 'Edit', edit_player_path(@resource), class:'mt-2 btn btn-outline-secondary' %>
      <%= link_to 'Back', :back, class: 'mt-2 btn btn-outline-secondary' %>
      <%= link_to 'Go to Players', players_path, class: 'mt-2 btn btn-outline-secondary' %>
    </div>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<nav class='navbar navbar-expand-lg navbar-dark bg-dark px-5'>
  <a class='navbar-brand' href='#'>Challenge</a>
  <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
    <span class='navbar-toggler-icon'></span>
  </button>

  <div class='collapse navbar-collapse flex-row-reverse' id='navbarSupportedContent'>
    <ul class='navbar-nav'>
      <li class='nav-item<%= controller_name == 'players' ? ' active' : '' %>'>
        <%= link_to 'Players', players_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to 'Devices', devices_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to 'Offers', offers_path, class: 'nav-link' %>

      </li>
      <li class='nav-item'>
        <%= link_to 'Offer targets', offer_targets_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>